# Generated by Django 3.1.5 on 2021-05-01 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleid', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('fever', models.BooleanField()),
                ('drycough', models.BooleanField()),
                ('tiredness', models.BooleanField()),
                ('difficultybreathing', models.BooleanField()),
                ('chestpain', models.BooleanField()),
                ('lossofspeech', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SampleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleid', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('SampleCollected', 'SampleColected'), ('TestingUnderProcess', 'TestingUnderProcess'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
