# Generated by Django 3.1.5 on 2021-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210502_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecollection',
            name='chestpain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='difficultybreathing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='drycough',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='fever',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='lossofspeech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='tiredness',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplestatus',
            name='status',
            field=models.CharField(choices=[('SampleCollected', 'SampleColected'), ('TestingUnderProcess', 'TestingUnderProcess'), ('Positive', 'Positive'), ('Negative', 'Negative')], default='SampleCollected', max_length=30),
        ),
    ]
